#!/usr/bin/env bash

# dcc-tools assumes this places
bin_dir="$HOME/.local/bin"

### Program info
###
name="hugo"
gh_url="https://github.com/gohugoio/${name}"
che_dir="$HOME/.cache/${name}"

### Server var
###
che_dir="$HOME/.cache/${name}"
bin_dir="$HOME/.local/bin"

## Install instructions
##
function install_program() {

    target_dir="$1"

    # get latest version url
    program_url=$(curl -w "%{url_effective}\n" -I -L -s -S "${gh_url}/releases/latest" -o /dev/null)

    # get latest tag
    program_tag="${program_url##*/}"

    # create cache
    mkdir -p "${che_dir}"

    # download binary file
    curl -s -L "${gh_url}/releases/download/${program_tag}/${name}_${program_tag}_linux-amd64.tar.gz" --output ${che_dir}/${name}.tar.gz

    # extract binary file to exec path
    tar -xf "${che_dir}/${name}.tar.gz" -C "${target_dir}"

    # remove unnecesary files
    rm "${target_dir}/README.md"
    rm "${target_dir}/LICENSE"

    # clean cache
    rmdir ${che_dir}

}

function remove_program() {

    local target_dir=$1

    if [[ -f "${target_dir}/${name}" ]] ; then
        rm "${target_dir}/${name}"
    fi
    
}

for arg in "$@"
do
    case $arg in
        install)
            shift
            install_program $1
            exit
            ;;
        remove)
            shift
            remove_program $1
            exit
            ;;
        *)
            ;;
    esac
done
