#!/usr/bin/env bash

### Program info
###
name="jq"
gh_url="https://github.com/jqlang/${name}"

### Server var
###

## Install instructions
##
function install_program() {

    target_dir="$1"

    # get latest version url
    program_url=$(curl -w "%{url_effective}\n" -I -L -s -S "${gh_url}/releases/latest" -o /dev/null)

    # get latest tag
    program_tag="${program_url##*/}"

    # download binary file
    curl -s -L "${gh_url}/releases/download/${program_tag}/${name}-linux-amd64.tar.gz" --output "${target_dir}/${name}"

}

for arg in "$@"
do
    case $arg in
        install)
            shift
            install_program "$1"
            exit
            ;;
        *)
            ;;
    esac
done
