#!/usr/bin/env bash

### Program info
###
name="zola"
gh_url="https://github.com/getzola/${name}"
che_dir="$HOME/.cache/${name}"

### Server var
###
che_dir="$HOME/.cache/${name}"

## Install instructions
##

function install_program() {

    target_dir="$1"

    # get latest version url
    program_url=$(curl -w "%{url_effective}\n" -I -L -s -S ${gh_url}/releases/latest -o /dev/null)

    # get latest tag
    program_tag="${program_url##*/}"

    # create cache
    mkdir -p "${che_dir}"

    # download binary file
    curl -s -L "${gh_url}/releases/download/${program_tag}/${name}-${program_tag}-x86_64-unknown-linux-gnu.tar.gz" --output "${che_dir}/${name}.tar.gz"

    # extract binary file to exec path
    tar -xf "${che_dir}/${name}.tar.gz" -C "${target_dir}"

    # clean cache
    rm "${che_dir}/${name}.tar.gz"
    rmdir "${che_dir}"

}

for arg in "$@"
do
    case $arg in
        install)
            shift
            install_program "$1"
            exit
            ;;
        *)
            ;;
    esac
done
